---
dns: # packetman -tbo 21 -p udp -w '.' 'google.com'
  :offset: 21
  :start_with_transport: true
  :offset_type: :bytes
  :wildcard: .
  :transport: udp

tcp_dns: # packetman -bo 15 -p tcp -w '.' 'google.com'
  :offset: 15
  :start_with_transport: false
  :offset_type: :bytes
  :wildcard: .
  :transport: tcp
