---
dns: # packetman -bo 13 -p udp -w '.' 'google.com'
  :offset: 13
  :start_with_transport: false
  :offset_type: :bytes
  :wildcard: .
  :transport: udp

dns_tcp: # packetman -bo 15 -p tcp -w '.' 'google.com'
  :offset: 15 # DNS over TCP adds a 2 byte length field to the beginning of the standard DNS protocol
  :start_with_transport: false
  :offset_type: :bytes
  :wildcard: .
  :transport: tcp
