---
tcp:
  table:
  - - :value: Source Port
      :colspan: 16
    - :value: Destination Port
      :colspan: 16
  - :separator
  - - :value: Sequence Number
      :colspan: 32
  - :separator
  - - :value: Acknowledgement Number
      :colspan: 32
  - :separator
  - - :value: Data Offset
      :colspan: 4
    - :value: RESERVED
      :colspan: 3
    - :value: ECN
      :colspan: 3
    - :value: Control Bits
      :colspan: 6
    - :value: Window
      :colspan: 16
  - :separator
  - - :value: Checksum
      :colspan: 16
    - :value: Urgent Pointer
      :colspan: 16
  - :separator
  - - :value: Options and Padding
      :colspan: 32
  payload_query: '((tcp[12:1] & 0xf0) >> 2)'
udp:
  table:
  - - :value: Source Port
      :colspan: 16
    - :value: Destination Port
      :colspan: 16
  - :separator
  - - :value: Length
      :colspan: 16
    - :value: Checksum
      :colspan: 16
  payload_query: 8
icmp:
  table:
  - - :value: Type
      :colspan: 8
    - :value: Code
      :colspan: 8
    - :value: Checksum
      :colspan: 16
  - :separator
  - - :value: Type Specific Options
      :colspan: 32
